// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrevoyanceInsight.Infrastructure.Persistence;

#nullable disable

namespace PrevoyanceInsight.Infrastructure.Migrations
{
    [DbContext(typeof(PrevoyanceDbContext))]
    [Migration("20260919095723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrevoyanceInsight.Domain.Entities.Beneficiaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnneeNaissance")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvoirVieillesse")
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SalaireAssure")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("beneficiaires", (string)null);
                });

            modelBuilder.Entity("PrevoyanceInsight.Domain.Entities.PlanPrevoyance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEntreeVigueur")
                        .HasColumnType("date");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreAssures")
                        .HasColumnType("integer");

                    b.Property<string>("Primaute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReglementDocumentId")
                        .HasColumnType("text");

                    b.Property<decimal>("TauxCotisationEmploye")
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("TauxCotisationEmployeur")
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("TauxCouverture")
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("TauxTechnique")
                        .HasColumnType("numeric(6,4)");

                    b.HasKey("Id");

                    b.ToTable("plans_prevoyance", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
